# Generated by Django 2.2 on 2019-07-08 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 7, 8, 7, 23, 15, 90774, tzinfo=utc))),
                ('modification_time', models.DateTimeField(default=datetime.datetime(2019, 7, 8, 7, 23, 15, 90805, tzinfo=utc))),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
